application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  trilloRTImage:
    type: string
    description: This is the Trillo Runtime Service image.
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  trilloDSImage:
    type: string
    description: This is the Trillo Data Service image.
    default: $REGISTRY/trillo-data-service:$TAG
    x-google-marketplace:
      type: IMAGE
  mysqlDBPassword:
    type: string
    title: MySQL Password
    description: MySQL password for the root account.
  redisCachePassword:
    type: string
    title: Redis Password
    description: Redis cache server password.

required:
- name
- namespace
- trilloDSImage
- trilloRTImage
- mysqlDBPassword
- redisCachePassword
