application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  trilloDSImage:
    type: string
    description: This is the Trillo Data Service image.
    default: gcr.io/trillo-k8s-public/trillo-rt/trillo-data-service:3.0
    x-google-marketplace:
      type: IMAGE
  trilloRTImage:
    type: string
    description: This is the Trillo Runtime Service image.
    default: gcr.io/trillo-k8s-public/trillo-rt:3.0
    x-google-marketplace:
      type: IMAGE
  reportingSecret:
    type: string
    default: /data/reporting_secret.yaml
    x-google-marketplace:
      type: REPORTING_SECRET
  mysqlDBPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
  redisCachePassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: base64EncodedPrivateKey
          base64EncodedCertificate: base64EncodedCertificate
required:
- name
- namespace
- reportingSecret


