properties:
  server:
    type: string
    x-google-marketplace:
      type: STRING
    default: data-test-internal
  bucket:
    type: string
    x-google-marketplace:
      type: STRING
    default: data-test-internal
  mysql.address:
    type: string
    x-google-marketplace:
      type: STRING
    default: data-test-internal
