apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-license
  namespace: {{ .Values.namespace }}
  labels:
    app: trillo-license
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.license.count }}
  selector:
    matchLabels:
      app: trillo-license
  template:
    metadata:
      name: trillo-license
      namespace: {{ .Values.namespace }}
      labels:
        app: trillo-license
    spec:
      containers:
        - name: trillo-addon-lic-agent
          image: gcr.io/project-trillort/trillo-addon-lic-agent:0.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: AGENT_LOCAL_PORT
              value: '6080'
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
        - image: gcr.io/cloud-marketplace-tools/metering/ubbagent
          name: ubbagent
          env:
            - name: AGENT_CONFIG_FILE
              value: /etc/ubbagent/config.yaml
            - name: AGENT_LOCAL_PORT
              value: "6080"
            - name: AGENT_STATE_DIR
              value: /var/lib/ubbagent
            - name: AGENT_REPORT_DIR
              value: /var/lib/ubbagent/reports
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: consumer-id
          volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
            - name: ubbagent-state
              mountPath: /var/lib/ubbagent
      volumes:
        - name: ubbagent-config
          configMap:
            name: agent-config
        - name: ubbagent-state
          emptyDir: { }
        - name: google-cloud-key
          secret:
            secretName: trillort-sa-key
