apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-rt
  namespace: {{ .Values.namespace }}
  labels:
    app: trillo-rt
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.rt.replicaCount }}
  template:
    metadata:
      name: trillo-rt
      namespace: {{ .Values.namespace }}
      labels:
        app: trillo-rt
        app.kubernetes.io/name: {{ .Release.Name }}
        version: {{ .Chart.Version }}
    spec:
      serviceAccountName: trillo-rt
      containers:
        - name: trillo-rt
          image: {{ .Values.rt.image.repo }}:{{ .Values.rt.image.tag }}
          imagePullPolicy: {{ .Values.rt.pullPolicy }}
          env:
            - name: TRILLO_PACKAGED_ORG_NAME
              value: {{ .Values.trilloPackagedOrgName }}
            - name: DEFAULT_APP
              value: {{ .Values.defaultApp }}
            - name: SERVICE_ENVIRONMENT
              value: {{ .Values.serviceEnvironment }}
            - name: DATA_SERVICE_URL
              value: https://trillo-ds.{{ .Values.namespace }}.svc.cluster.local:443
            - name: TRILLO_USE_REDIS
              value: 'true'
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
            - name: REDIS_CREDENTIALS
              value: $REDIS_CREDENTIALS
            - name: SERVICE_RUNNING_IN_GCP
              value: 'true'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: GCP_BUCKET_NAME
              value: {{ .Values.bucket }}
            - name: GCP_SERVICE_NAME
              value: _default_
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: TOKEN-SECRET
              valueFrom:
                secretKeyRef:
                  name: web-token-secret
                  key: secret
            - name: QUARTZ_ENABLED
              value: '{{ .Values.rt.quartz.enabled }}'
            - name: QUARTZ_CLUSTERED
              value: '{{ .Values.rt.quartz.clustered }}'
            - name: SERVER_PUBLIC_URL
              value: https://{{ .Values.uiserver }}
            - name: TRILLO_WORKBENCH_UI_URL
              value: https://{{ .Values.uiserver }}
            - name: DT_URL
              value: https://design.trillo.io
            - name: REPO_DIR
              value: "{{ .Values.nfsMount }}/repo"
            - name: APPDATA_DIR
              value: "{{ .Values.nfsMount }}/data"
            - name: GCS_FILE_SERVER
              value: {{ .Values.edge.ipaddress }}
            - name: GCS_FILE_SERVER_USER
              value: {{ .Values.edge.username }}
            - name: RSA_PRIVATE_KEY
              value: /etc/ssh-key/trillo-ssh
            - name: MAIL_ENABLED
              value: '{{ .Values.mail.enabled }}'
            - name: MAIL_FROM
              value: 'no-reply@{{ .Values.server }}'
            - name: LOGGING_CONFIG
              value: /var/rt-logs-config/log4j2.xml
          ports:
            - containerPort: 8020
              name: trillo-rt
          volumeMounts:
            - name: trillo-nfs-volume
              mountPath: {{ .Values.nfsMount }}
            - name: ssh-key-volume
              mountPath: "/etc/ssh-key"
              readOnly: true
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: rt-logs-config-volume
              mountPath: /var/rt-logs-config
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 6
            httpGet:
              scheme: HTTPS
              path: /_healthcheck
              port: 8020
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 6
            httpGet:
              path: /_healthcheck
              scheme: HTTPS
              port: 8020
      restartPolicy: Always
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: trillo-ssh-secret
            defaultMode: 256
        - name: trillo-nfs-volume
          nfs:
            server: trillo-nfs.{{ .Values.namespace }}.svc.cluster.local
            path: /
        - name: google-cloud-key
          secret:
            secretName: trillort-sa-key
        - name: rt-logs-config-volume
          configMap:
            name: rt-logs-config
  selector:
    matchLabels:
      app: trillo-rt
---
apiVersion: v1
kind: Service
metadata:
  name: trillo-rt
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
  annotations:
    cloud.google.com/app-protocols: '{"trillo-rt-https":"HTTPS"}'
    cloud.google.com/backend-config: '{"default": "rt-bkendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: trillo-rt
  ports:
    - name: trillo-rt-https
      protocol: TCP
      port: 8020
      targetPort: 8020
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: trillort-ip
    networking.gke.io/managed-certificates: trillo-certificate
    networking.gke.io/v1beta1.FrontendConfig: rt-frontend-config
spec:
  rules:
    - host: {{ .Values.server }}
      http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: trillo-rt
              port:
                number: 8020
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: rt-frontend-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trillo-rt
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trillo-rt-role-binding
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit # Allows read/write access to most objects in a namespace. It does not allow viewing or modifying roles or rolebindings.
subjects:
  - kind: ServiceAccount
    name: trillo-rt
    namespace: {{ .Values.namespace }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: trillo-certificate
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  domains:
    - {{ .Values.server }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: rt-bkendconfig
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rt-logs-config
  namespace: {{ .Values.namespace }}
data:
  log4j2.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>

    <Configuration shutdownHook="disable">
      <Properties>
        <Property name="appenderPatternLayout">
          TRILLO-RT %p \(%file:%line\) %msg%n
        </Property>
      </Properties>

      <Appenders>
        <Console name="Stdout" target="SYSTEM_OUT">
          <PatternLayout pattern="${appenderPatternLayout}"/>
        </Console>
        <RollingRandomAccessFile name="RollingAppender"
          fileName="logs/trillo.log" filePattern="logs/trillo-%d{yyyyMMdd}.log.gz">
          <PatternLayout pattern="${appenderPatternLayout}"/>
          <TimeBasedTriggeringPolicy/>
          <DefaultRolloverStrategy max="3"/>
        </RollingRandomAccessFile>

      </Appenders>
      <Loggers>

        <!-- Application Loggers -->
        <Logger name="com.collager.trillo" level="INFO"/>
        <Logger name="com.collager.app" level="INFO"/>

        <!-- 3rdparty Loggers -->
        <Logger name="org.springframework.core" level="WARN"/>
        <Logger name="org.springframework.beans" level="WARN"/>
        <Logger name="org.springframework.context" level="WARN"/>
        <Logger name="org.springframework.web" level="WARN"/>
        <Logger name="springfox.documentation" level="WARN"/>
        <Logger name="o.a.c.b.converters" level="INFO"/>
        <Logger name="org.springframework.web.socket.config.WebSocketMessageBrokerStats" level="WARN"/>

        <!-- Root Logger -->
        <Root level="INFO">
          <AppenderRef ref="RollingAppender"/>
          <AppenderRef ref="Stdout"/>
        </Root>

      </Loggers>
    </Configuration>
