---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: trillo-ui
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      name: trillo-ui
      namespace: {{ .Values.namespace }}
      labels:
        app: trillo-ui
        app.kubernetes.io/name: {{ .Release.Name }}
        version: {{ .Chart.Version }}
    spec:
      containers:
        - name: trillo-ui
          image: {{ .Values.ui.image.repo }}:{{ .Values.ui.image.tag }}
          imagePullPolicy: {{ .Values.ui.pullPolicy }}
          ports:
            - containerPort: 80
              name: trillo-ui
          envFrom:
          - configMapRef:
             name: trillo-ui-config
  selector:
    matchLabels:
      app: trillo-ui
---
apiVersion: v1
kind: Service
metadata:
  name: trillo-ui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: trillo-ui
  ports:
    - name: trillo-ui-https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: trilloui-ip
    networking.gke.io/managed-certificates: trillo-ui-certificate
    networking.gke.io/v1beta1.FrontendConfig: ui-frontend-config
spec:
  rules:
    - host: {{ .Values.uiserver }}
      http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: trillo-ui
              port:
                number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ui-frontend-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: trillo-ui-certificate
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  domains:
    - {{ .Values.uiserver }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: trillo-ui-config
  namespace: {{ .Values.namespace }}
data:
  BaseURL: https://{{ .Values.server }}
  Title: "Trillo Apps"
  AccessToken: lsTrilloAppsAccessToken