apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-pubsub
  namespace: {{ .Values.namespace }}
  labels:
    app: trillo-pubsub
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.pubsub.replicaCount }}
  selector:
    matchLabels:
      app: trillo-pubsub
  template:
    metadata:
      name: trillo-pubsub
      namespace: {{ .Values.namespace }}
      labels:
        app: trillo-pubsub
    spec:
      containers:
        - name: trillo-pubsub
          image: {{ .Values.pubsub.image }}
          imagePullPolicy: {{ .Values.pubsub.pullPolicy }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: CONFIG_JSON
              value: /var/pubsub/config.json
            - name: TRILLO_SVCUSER_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: admin-credentials
                  key: password
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: trillo-pubsub-config
              mountPath: /var/pubsub
      volumes:
        - name: google-cloud-key
          secret:
            secretName: trillort-sa-key
        - name: trillo-pubsub-config
          configMap:
            name: trillo-pubsub
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: trillo-pubsub
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
    {
      "configs": [
        {
          "class": "PubSubWatcher",
          "enabled": true,
          "serviceName" : "trillo-ds.{{ .Values.namespace }}.svc.cluster.local",
          "servicePort" : 443,
          "tokenUri": "authds/token",
          "client_id": "cloud_api_client",
          "username": "svcuser",
          "x-org-name": "cloud",
          "x-app-name": "filesharing",
          "subscriptionId": "trillo-gcs-sub",
          "targetUri": {
            "CREATE": "foldersvc/cloudstorage/folder/folderOrFileCreated",
            "ARCHIVE_DELETE": "foldersvc/cloudstorage/folder/folderOrFileDeleted"
          }
        }
      ]
    }