apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-nfs
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    app: trillo-nfs
spec:
  replicas: 1
  template:
    metadata:
      name: trillo-nfs
      namespace: {{ .Values.namespace }}
      labels:
        app: trillo-nfs
    spec:
      containers:
      - name: trillo-nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - name: nfs-volume
            mountPath: /exports
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
  selector:
    matchLabels:
      app: trillo-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: trillo-nfs
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    app: trillo-nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  type: ClusterIP # Internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi