{{- if ne .Values.server "data-test-internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillo-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    app: trillo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trillo-redis
  template:
    metadata:
      name: trillo-redis
      namespace: {{ .Values.namespace }}
      labels:
        app: trillo-redis
    spec:
      containers:
        - image: redis:6.2.6
          name: trillo-redis
          command:
            - "redis-server"
          env:
            - name: REDIS_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          args:
            - "--requirepass"
            - "$(REDIS_CREDENTIALS)"
            - "--appendonly"
            - "yes"
          ports:
            - containerPort: 6379
              name: trillo-redis
          volumeMounts:
            - name: trillo-nfs-volume
              mountPath: {{ .Values.nfsMount }}/data
      volumes:
        - name: trillo-nfs-volume
          nfs:
            server: trillo-nfs.{{ .Values.namespace }}.svc.cluster.local
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: trillo-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: trillo-redis
    app.kubernetes.io/name: {{ .Release.Name }}
    version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: trillo-redis
{{- end }}