x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
<<<<<<< HEAD
  publishedVersion: "3.11.8"
=======
  publishedVersion: "3.11.7"
>>>>>>> 3ea1d483df21cd826dec46c1314813bbb1b4c755
  publishedVersionMetadata:
    releaseNote: >-
      Major release of Trillo Apps.
  images: 
    '':  # Primary image has no name.
      properties:
        rt.image.repo:
          type: REPO_WITH_REGISTRY
        rt.image.tag:
          type: TAG
    trillo-data-service:
      properties:
        ds.image.repo:
          type: REPO_WITH_REGISTRY
        ds.image.tag:
          type: TAG
    trillo-gke-tasker:      
      properties:
        pubsub.image.repo:
          type: REPO_WITH_REGISTRY
        pubsub.image.tag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: trillo
    x-google-marketplace:
      type: NAMESPACE
  server:
    title: Server DNS name 
    description: Full domain name of the server, e.g. cg.example.com
    type: string
    x-google-marketplace:
      type: STRING
    default: trillo-rt.svc.cluster.local
  bucket:
    title: Bucket Name 
    description: Bucket name provisioned by the pre-installer
    type: string
    x-google-marketplace:
      type: STRING
    default: -na-
  mysql.address:
    title: CloudSQL server  
    description: Private IP of the MySQL server provisioned by the pre-installer
    type: string
    x-google-marketplace:
      type: STRING
    default: -na-
  edge.ipaddress:
    title: SFTP server  
    description: SFTP server is provisioned by the pre-installer. Leave it blank if there is none provisioned.
    type: string
    x-google-marketplace:
      type: STRING
    default: -na-
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
required:
- name
- namespace
- server
- bucket
- mysql.address
- reportingSecret
