apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: $namespace
  labels:
    app.kubernetes.io/name: "$APP_INSTANCE_NAME"
data:
  config.yaml: |
    identities:
    - name: gcp
      gcp:
        encodedServiceAccountKey: $AGENT_ENCODED_KEY
    metrics:
    - name: container_time
      type: int
      aggregation:
        bufferSeconds: 60
      endpoints:
      - name: disk
      - name: servicecontrol
    endpoints:
    - name: disk
      disk:
        reportDir: $AGENT_REPORT_DIR
        expireSeconds: 3600
    - name: servicecontrol
      servicecontrol:
        identity: gcp
        serviceName: trillo-platform.mp-trillo-k8s-public.appspot.com
        consumerId: $AGENT_CONSUMER_ID
